/*
 * This file was generated by the Gradle 'init' task.
 */
pluginManagement {
    repositories {
        maven { url = uri("https://repo.spring.io/milestone") }
        gradlePluginPortal()
    }
}

rootProject.name = "unicorn-swarm"
include(":spring-cloud-lwohvye-config-3344")
include(":spring-cloud-lwohvye-provider-config-client")
include(":spring-cloud-lwohvye-eureka-7001")
include(":spring-cloud-lwohvye-gateway")
include(":spring-cloud-lwohvye-config-client-3355")
include(":spring-cloud-lwohvye-consumer-config-client")
include(":spring-cloud-lwohvye-api")
include(":spring-cloud-lwohvye-websocket")
