/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.lwohvye.springcloud.java-conventions")
    id("org.springframework.boot") version "3.2.0-M3"
    id("io.spring.dependency-management") version "1.1.3"
    id("io.freefair.lombok") version "8.3"
}

extra["springCloudVersion"] = "2023.0.0-M2"

dependencyManagement {
    imports {
        mavenBom("org.springframework.cloud:spring-cloud-dependencies:${property("springCloudVersion")}")
    }
}

dependencies {
    api(project(":spring-cloud-lwohvye-api"))
    api("org.springframework.boot:spring-boot-devtools")
    api("org.springframework.boot:spring-boot-starter-actuator")
    api("org.springframework.boot:spring-boot-starter-web")
    api("org.springframework.boot:spring-boot-starter-undertow")
    api("org.springframework.boot:spring-boot-starter-aop")
    api("org.apache.commons:commons-pool2")
    api("org.springframework.cloud:spring-cloud-starter-netflix-eureka-client")
    api("org.springframework.cloud:spring-cloud-starter-config")
    api("org.springframework.cloud:spring-cloud-starter-bus-amqp")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

group = "spring-cloud-lwohvye"
description = "spring-cloud-lwohvye-provider-config-client"
